#!/usr/bin/env bash
# Optional STCP tunnel through the existing OpenResty ssl_preread listener.
set -Eeuo pipefail
umask 027

FRP_VERSION=0.71.0
FRP_SHA256=84f27e39f11169f7adcef8e8b70c9329de17747b1f14dad9fb95eef5682ea716
SERVER_HOST=${FRP_SERVER_HOST:?Set FRP_SERVER_HOST to the SSH/public server hostname}
TLS_NAME=${FRP_TLS_SERVER_NAME:-frp-tunnel.$SERVER_HOST}
BASE=/serverdata/frp
STREAM_CONFIG=${FRP_STREAM_CONFIG:-/serverdata/1panel/www/stream.d/tls-forward-443.conf}
EXPORT_DIR=/root/.config/frp-tunnel

[[ $EUID -eq 0 ]] || { echo 'Run this script as root.' >&2; exit 1; }
[[ $(uname -m) == x86_64 ]] || { echo 'This installer supports amd64 only.' >&2; exit 1; }
[[ $SERVER_HOST =~ ^[a-zA-Z0-9][a-zA-Z0-9.-]+$ && $TLS_NAME =~ ^[a-zA-Z0-9][a-zA-Z0-9.-]+$ ]] || {
    echo 'Hostnames must contain only letters, numbers, dots and hyphens.' >&2; exit 1;
}
[[ -f $STREAM_CONFIG ]] || { echo "Missing stream config: $STREAM_CONFIG" >&2; exit 1; }
for command in curl tar openssl sha256sum python3 docker; do
    command -v "$command" >/dev/null || { echo "Missing command: $command" >&2; exit 1; }
done
mapfile -t containers < <(docker ps --format '{{.Names}}' | sed -n '/^1Panel-openresty-/p')
[[ ${#containers[@]} -eq 1 ]] || { echo 'Expected one running 1Panel OpenResty container.' >&2; exit 1; }
OPENRESTY=${containers[0]}

if [[ -f $BASE/deployment.env ]]; then
    # This file is generated by this script and contains no secrets.
    grep -Fxq "SERVER_HOST=$SERVER_HOST" "$BASE/deployment.env" &&
        grep -Fxq "TLS_NAME=$TLS_NAME" "$BASE/deployment.env" || {
        echo 'Existing deployment uses different hostnames; migrate it explicitly.' >&2; exit 1;
    }
elif [[ -e $BASE ]]; then
    echo "$BASE already exists and is not managed by this installer." >&2; exit 1
fi

temp_dir=$(mktemp -d)
trap 'rm -rf -- "$temp_dir"' EXIT
if [[ ! -x /usr/local/bin/frps || $(/usr/local/bin/frps --version) != "$FRP_VERSION" ||
      ! -x /usr/local/bin/frpc || $(/usr/local/bin/frpc --version) != "$FRP_VERSION" ]]; then
    curl -fSL --retry 3 --connect-timeout 15 --max-time 180 \
        "https://github.com/fatedier/frp/releases/download/v$FRP_VERSION/frp_${FRP_VERSION}_linux_amd64.tar.gz" \
        -o "$temp_dir/frp.tar.gz"
    printf '%s  %s\n' "$FRP_SHA256" "$temp_dir/frp.tar.gz" | sha256sum --check --status
    tar -xzf "$temp_dir/frp.tar.gz" -C "$temp_dir"
    install -m 0755 "$temp_dir/frp_${FRP_VERSION}_linux_amd64/frps" /usr/local/bin/frps
    install -m 0755 "$temp_dir/frp_${FRP_VERSION}_linux_amd64/frpc" /usr/local/bin/frpc
fi

getent group frp >/dev/null || groupadd --system frp
id frp >/dev/null 2>&1 || useradd --system --gid frp --no-create-home --home-dir /nonexistent --shell /usr/sbin/nologin frp
install -d -m 0750 -o root -g frp "$BASE" "$BASE/pki"
install -d -m 0700 "$EXPORT_DIR" "$EXPORT_DIR/visitor"
printf 'SERVER_HOST=%s\nTLS_NAME=%s\n' "$SERVER_HOST" "$TLS_NAME" > "$BASE/deployment.env"

if [[ ! -f $BASE/token ]]; then openssl rand -hex 32 > "$BASE/token"; fi
if [[ ! -f $BASE/secret ]]; then openssl rand -hex 32 > "$BASE/secret"; fi
token=$(cat "$BASE/token")
secret=$(cat "$BASE/secret")

if [[ ! -f $BASE/pki/ca.crt ]]; then
    openssl req -x509 -newkey rsa:3072 -nodes -sha256 -days 3650 \
        -keyout "$BASE/pki/ca.key" -out "$BASE/pki/ca.crt" \
        -subj '/CN=MyScripts FRP private CA' \
        -addext 'basicConstraints=critical,CA:TRUE' -addext 'keyUsage=critical,keyCertSign,cRLSign' \
        >"$temp_dir/openssl.log" 2>&1
fi
chmod 0600 "$BASE/pki/ca.key"
issue_cert() {
    local name=$1 usage=$2
    [[ -f $BASE/pki/$name.crt ]] && return
    openssl req -new -newkey rsa:2048 -nodes -sha256 \
        -keyout "$BASE/pki/$name.key" -out "$temp_dir/$name.csr" -subj "/CN=$name" \
        >"$temp_dir/openssl.log" 2>&1
    printf 'basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature,keyEncipherment\nextendedKeyUsage=%s\n' "$usage" > "$temp_dir/extensions"
    if [[ $name == server ]]; then printf 'subjectAltName=DNS:%s\n' "$TLS_NAME" >> "$temp_dir/extensions"; fi
    openssl x509 -req -in "$temp_dir/$name.csr" -CA "$BASE/pki/ca.crt" -CAkey "$BASE/pki/ca.key" \
        -CAcreateserial -out "$BASE/pki/$name.crt" -days 1825 -sha256 -extfile "$temp_dir/extensions" \
        >"$temp_dir/openssl.log" 2>&1
}
issue_cert server serverAuth
issue_cert service clientAuth
issue_cert visitor clientAuth
for name in server service visitor; do
    openssl x509 -in "$BASE/pki/$name.crt" -checkend 2592000 -noout >/dev/null || {
        echo "$name certificate expires within 30 days; reissue it and redistribute the visitor bundle." >&2; exit 1;
    }
done

cat > "$BASE/frps.toml" <<EOF
bindAddr = "127.0.0.1"
bindPort = 7000
proxyBindAddr = "127.0.0.1"
auth.method = "token"
auth.token = "$token"
auth.additionalScopes = ["HeartBeats", "NewWorkConns"]
transport.tls.force = true
transport.tls.certFile = "$BASE/pki/server.crt"
transport.tls.keyFile = "$BASE/pki/server.key"
transport.tls.trustedCaFile = "$BASE/pki/ca.crt"
log.to = "console"
log.level = "info"
log.disablePrintColor = true
EOF
cat > "$BASE/frpc-service.toml" <<EOF
serverAddr = "127.0.0.1"
serverPort = 7000
loginFailExit = false
auth.method = "token"
auth.token = "$token"
auth.additionalScopes = ["HeartBeats", "NewWorkConns"]
transport.tls.enable = true
transport.tls.certFile = "$BASE/pki/service.crt"
transport.tls.keyFile = "$BASE/pki/service.key"
transport.tls.trustedCaFile = "$BASE/pki/ca.crt"
transport.tls.serverName = "$TLS_NAME"
log.to = "console"
log.level = "info"
log.disablePrintColor = true

[[proxies]]
name = "https-preread"
type = "stcp"
secretKey = "$secret"
localIP = "127.0.0.1"
localPort = 443
transport.useEncryption = true
EOF
cat > "$EXPORT_DIR/visitor/visitor.toml" <<EOF
serverAddr = "$SERVER_HOST"
serverPort = 443
loginFailExit = false
auth.method = "token"
auth.token = "$token"
auth.additionalScopes = ["HeartBeats", "NewWorkConns"]
transport.tls.enable = true
transport.tls.disableCustomTLSFirstByte = true
transport.tls.certFile = "visitor.crt"
transport.tls.keyFile = "visitor.key"
transport.tls.trustedCaFile = "ca.crt"
transport.tls.serverName = "$TLS_NAME"
log.to = "console"
log.level = "info"
log.disablePrintColor = true

[[visitors]]
name = "https-preread-visitor"
type = "stcp"
serverName = "https-preread"
secretKey = "$secret"
bindAddr = "127.0.0.1"
bindPort = 443
transport.useEncryption = true
EOF
install -m 0600 "$BASE/pki/visitor.key" "$EXPORT_DIR/visitor/visitor.key"
install -m 0600 "$BASE/pki/visitor.crt" "$EXPORT_DIR/visitor/visitor.crt"
install -m 0600 "$BASE/pki/ca.crt" "$EXPORT_DIR/visitor/ca.crt"
chmod 0600 "$EXPORT_DIR/visitor/visitor.toml"
chgrp frp "$BASE"/*.toml "$BASE/token" "$BASE/secret" "$BASE/pki"/*.crt "$BASE/pki/server.key" "$BASE/pki/service.key"
chmod 0640 "$BASE"/*.toml "$BASE/token" "$BASE/secret" "$BASE/pki"/*.crt "$BASE/pki/server.key" "$BASE/pki/service.key"
chmod 0600 "$BASE/pki/visitor.key"
/usr/local/bin/frps verify -c "$BASE/frps.toml"
/usr/local/bin/frpc verify -c "$BASE/frpc-service.toml"
(cd "$EXPORT_DIR/visitor"; /usr/local/bin/frpc verify -c visitor.toml)

for service in frps frpc-service; do
    cat > "/etc/systemd/system/$service.service" <<EOF
[Unit]
Description=MyScripts FRP $service
Wants=network-online.target
After=network-online.target
StartLimitIntervalSec=0

[Service]
User=frp
Group=frp
ExecStart=/usr/local/bin/${service%%-*} -c $BASE/$service.toml
Restart=always
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
UMask=0077

[Install]
WantedBy=multi-user.target
EOF
done
systemctl daemon-reload
systemctl enable frps frpc-service
systemctl restart frps frpc-service

cp -a "$STREAM_CONFIG" "$temp_dir/stream.before"
python3 - "$STREAM_CONFIG" "$TLS_NAME" <<'PY'
import os, re, sys, tempfile
path, name = sys.argv[1:]
text = open(path).read()
match = re.search(r'map\s+\$ssl_preread_server_name\s+\$tls_18443_upstream\s*\{', text)
if not match:
    raise SystemExit('Expected ssl_preread map was not found.')
entry = re.search(r'^\s*' + re.escape(name) + r'\s+([^;]+);', text, re.M)
if entry and entry.group(1).strip() != '127.0.0.1:7000':
    raise SystemExit('Tunnel SNI already has a different destination.')
if not entry:
    text = text[:match.end()] + '\n    ' + name + '  127.0.0.1:7000; # MyScripts FRP tunnel\n' + text[match.end():]
    stat = os.stat(path)
    fd, temporary = tempfile.mkstemp(dir=os.path.dirname(path))
    with os.fdopen(fd, 'w') as output:
        output.write(text)
    os.chmod(temporary, stat.st_mode)
    os.chown(temporary, stat.st_uid, stat.st_gid)
    os.replace(temporary, path)
PY
if ! docker exec "$OPENRESTY" nginx -t || ! docker exec "$OPENRESTY" nginx -s reload; then
    cp -a "$temp_dir/stream.before" "$STREAM_CONFIG"
    echo 'OpenResty validation/reload failed; restored its previous config.' >&2; exit 1
fi
if [[ ! -f $EXPORT_DIR/stream.before-frp.conf ]]; then
    install -m 0600 "$temp_dir/stream.before" "$EXPORT_DIR/stream.before-frp.conf"
fi
tar -czf "$EXPORT_DIR/visitor-client.tar.gz" -C "$EXPORT_DIR/visitor" visitor.toml ca.crt visitor.crt visitor.key
chmod 0600 "$EXPORT_DIR/visitor-client.tar.gz"
systemctl is-active frps frpc-service
echo "Installed FRP $FRP_VERSION. Public TLS SNI: $TLS_NAME on TCP 443."
echo "Private visitor bundle: $EXPORT_DIR/visitor-client.tar.gz (contains secrets; do not commit/share)."
